### ISSUE TITLE
[Linux:Budgie] Tray icon way too big

### ISSUE THREAD

**Issue by dhaavi** [safing/portmaster-ui#111]
The tray icon is not scaled down by budgie, which then breaks the whole task bar.

**Comment by dreamcat4** [comment]
got the same problem!

Looking here:

```sh
$ cat portmaster_notifier.desktop 
[Desktop Entry]
Name=Portmaster Notifier
GenericName=Application Firewall Notifier
Exec=/var/lib/portmaster/portmaster-start notifier --data=/var/lib/portmaster
Icon=portmaster
Terminal=false
Type=Application
Categories=System
```

it shows the same binary is `portmaster-start`. And the 'Icon' specified in the `.desktop` file is simply `portmaster`. However when i changed this icon it didn't seem to do anything. So could it be the tray notifier is getting a different icon for the tray? From somewhere else perhaps?

```sh
$ /var/lib/portmaster/portmaster-start show notifier
/var/lib/portmaster/updates/linux_amd64/notifier/portmaster-notifier_v0-2-3 --data /var/lib/portmaster
```

Hmm ok...

It appears that the tray icon is baked into the Go binary itself right? That these assets are defined here:

https://github.com/safing/portmaster-ui/tree/develop/notifier/icons

So it is not be possible to fix this issue... without recompiling the go binary?

**Comment by dreamcat4** [comment]
![Screenshot from 2021-05-23 23-05-20](https://user-images.githubusercontent.com/63074/119278188-8f584e00-bc1b-11eb-8469-c7a1e90f5174.png)

**Comment by dreamcat4** [comment]
like...

i can see here you are using a go library `getlantern/systray` for this

https://github.com/safing/portmaster-ui/blob/develop/notifier/tray.go#L13

and in your `tray.go` file, it has various states to update the icon color for red, yellow, green etc. Ok then...

it seems the API interface for the go library you are using specifies a bitmap data. Which is why you are creating the icons as PNG bitmap images... OK i see that. And then the go library you use is calling out to the `libappindicator` library here:

https://github.com/getlantern/systray/blob/master/systray_linux.c

To actually do the icon. So then i look there and find its all GTK code stuff (which IDK) but also....

https://github.com/linuxmint/libappindicator/blob/master/src/app-indicator.c#L1688

seems to indicate maybe there is a way to send the GTK icon as SVG perhaps maybe that could help IDK?

You know, if then the icon is rendered size agnostic as a vector. And with some quality. However all these APIs just dont advertise this and its all pretty darned squiffy

I have been researching this issue all evening. And have collected many links. However still no closer to finding the correct answer. It's all way overcomplicated if you ask me... all for displaying a simple icon. dear dear

Honestly i don't think most of the developers really understand any of this either. So what to do eh? you see, for any other program i can edit the tray icon myself. And force it to be the right size. However this program uses bitmaps, and compiles the icon data into the program itself. Then under the hood the libs all uses a bunch of poorly documented APIs that is all really wonky if you ask me

any help here?

**Comment by dhaavi** [comment]
Hey @dreamcat4, nice work getting into this!

I looked into this too and am also not sure why Budgie does not handle this correctly - or why and how we don't supply the correct data. From what I know `.svg`s are not compatible.

The main thing I don't get is that every other desktop environment is just fine with our 512x512 icons.
I will try to just downscale the icon size to 32x32 in the coming weeks and see if that works.

If you want to, you can also try this yourself and see what happens.

We might make more direct use of OS interfaces for this part of the notifier in the future, but right now we really need progress on all sides.

Regarding making the image paths customizable, I don't think we can do this with our current library.

**Comment by dhaavi** [comment]
I gathered some Icon sizing information:
- 22px from https://github.com/UbuntuBudgie/budgie-indicator-applet/issues/18
- 16px to 24px from https://github.com/UbuntuBudgie/budgie-indicator-applet/issues/25

I guess we should maybe detect if we are on budgie and use a scaled down icon there. I did not find a spec where this is actually defined. As mentioned in the release notes (wt..?) I will probably go with an icon size of 22px. I think this will do the job.

Only thing left is to find out how to only do this on budgie, as all the others might actually want to use bigger icons.

**Comment by dreamcat4** [comment]
Hey there, IDK if this can be any help here to look at (as an example).... but there is 1 program which know use SVG for the tray icon:

albert launcher

So depending on the code, and how is done over there. It might be helpful to see. Because clearly for HiDPI displays and changing the display scaling is more desirable. Which is what seems the reason here for your 512px PNG image.

On the budgie side of things I hope you can also work with @fossfreedom to convey a better understanding how you swap and update the tray icon. To change the color. If it triggers what sorts of update event. To know if there is the opportunity to have a callback() method on the DE side to re-scale the image. Or if not possible then you need to scale the icon image yourself before swapping it over.

However I really hope you can have some easy solution for SVG instead. If it does not have to come to that. :+1:

**Comment by dreamcat4** [comment]
Ah... it seems albert can do SVG icon because it depends upon QT5 libraries frameworks. And pulls in and uses those QT classes like `QIcon` etc. Clearly you do not want to depend on some heavy set of frameworks here. Because it's a standalone Go binary. However it would still be interesting to know how QT does it. They just have such a massive codebase I did not dig further...

But I am looking elsewhere and will keep you updated if anything turns up :+1:

**Comment by dhaavi** [comment]
When reading through all these issues surrounding that, someone mentioned at some point that SVGs are just rendered to a 22px png, which is then used for the icon. So I think I'll be moving forward with just adding an small png for Budgie, as that is what the library we currently use supports.

I've already tried supplying an .ico instead, which should work according to the lib docs, but it totally screws up the icon on Gnome.

Do you know, does this affect all distros with Budgie, or just Ubuntu Budgie?

**Comment by dreamcat4** [comment]
This tray notifier widget program is made and distributed for Ubuntu Budgue only. However apparently it may also be similar code... and therefore may have similar bugs in MATE but that is only a rumor I cannot verify it's the case for this situation. Perhaps you already tested yourself with MATE and will know.

The Solus (Upstream project) has recently rewritten their Tray app

https://github.com/solus-project/budgie-desktop/issues/2030#issuecomment-848041145

But again, I have not used it myself, and I have no idea what X-Embed means either, sorry! But their replacement app being so new ATM it may have it's own different set of bugs issues that have not been seen before.

It's still 'unclear' to me (at this point in time) whether downstream 'Ubuntu Budgie' flavor will take the new tray app from Solus. IDK.

But your decision to smallen the icon to 22px definately sounds like a good option (for myself). It just is not quite so good for certain other people using HiDPI / retina displays ;)

Thanks for trying to help. It's really not your fault. Maybe in future there is some way to ask a query to the DE, to find out what icon size they need to be given. Before doing the scaling operation and actually displaying the icon etc. Of course the standards - what standards? Yeah. What a mess. But that is the type of a new feature request... which we would ideally want to ask for the go library (that go lib you are calling here, which then calls the libappindicator C lib).

**Comment by dhaavi** [comment]
Thanks @fossfreedom for chiming in here and clarifying this for us!

I think the best way to move forward is to use the small icon size only on systems where it is confirmed that there are issues with the big size.

**Comment by dreamcat4** [comment]
@dhaavi this issue is now fixed in budgie, long time bug

https://github.com/UbuntuBudgie/budgie-indicator-applet/issues/18#ref-commit-78d7710

**Comment by dhaavi** [comment]
Nice! Thanks for the update!

For anyone still experiencing this bug:
It was fixed in [v0.7.0](https://github.com/UbuntuBudgie/budgie-indicator-applet/releases/tag/v0.7.0) of the [Ubuntu Budgie Indicator Applet](https://github.com/UbuntuBudgie/budgie-indicator-applet). Please make sure you have that version installed.
However, I don't know when this version will be released into the apt repos.

Closing this now, as it was fixed by the affected software.
